function doActionsForHide(b){b=b.attr("id");if(b==="home"){try{$("#videoportada embed").get(0).pauseVideo()}catch(c){}$("#videoportada").hide()}b==="impactes"&&($("#impactes .accordion-toggle h3.main").text(__VOBRES.petjades_title),$("#impactes .accordion-toggle h3.sub").text(""));if(b==="testimonis"){var e=$("#videotestimoni embed").get(0);if(e)try{e.pauseVideo()}catch(f){}}b==="miratges"&&(b=$("#miratges .item.active .parellaFotos"))&&b.hide()}
function doActionsForShow(b){b=b.attr("id");if(b==="home"){$("#impactesnav .back").toggleClass("active",!1);$("#impactesnav .forward").toggleClass("active",!0);$("#impactesnav .mapa").toggleClass("active",!1);$("#bigone").toggleClass("dissolve",!0);$("#map").toggleClass("dissolve",!1);$("#impactesCarousel").carousel(0);$("#impactes .accordion-toggle h3.main").text(__VOBRES.petjades_title);$("#impactes .accordion-toggle h3.sub").text("");$("#videoportada").show();try{$("#videoportada embed").get(0).playVideo()}catch(c){}}if(b===
"miratges")if(__VOBRES.loaded[b]){var e=$("#miratges .item.active .parellaFotos");e&&e.show()}else{var e="01,02,03,04,05,06,07,08,09,10,11,12,13,14".split(","),f=getAvailableSize("miratges")-200;for(m=0;m<e.length;m++){$miratge=$("#item-"+e[m]);$parella=$("#parella-"+e[m]);var g=$parella.find("img").width(),d=$parella.find("img").height(),g=Math.floor(f*(g/d));$miratge.find(".title").css({width:g});$miratge.find(".peus").css({width:g});d=$parella.find("img");$(d.get(0)).css({width:g,height:f});$(d.get(1)).css({width:g,
height:f});$miratge.css({"margin-left":Math.floor((1170-g)/2)});g=$("html").attr("lang")!="ca"?"../":"";$parella.beforeAfter({showFullLinks:!1,imagePath:g+"img/"})}}if(b==="testimonis")if($("#testimonis .video").css({height:getAvailableSize("testimonis")-200}),playingvideo=$("#videotestimoni embed").get(0))try{playingvideo.playVideo()}catch(k){}else $("#testimonis .firsttime").trigger("click")}
function hideSection(b){var c=b.find(".accordion-body");doActionsForHide(b);c.animate({height:0},function(){b.toggleClass("visible",!1)})}
function showSection(b){var c=b.find(".accordion-body"),e=c.find(".accordion-inner"),f=b.attr("id"),g=getAvailableSize(f);c.animate({height:g});b.toggleClass("visible",!0);$("#accordion2").toggleClass("athome",f==="home");__VOBRES.loaded[f]?(console.log("already loaded"),doActionsForShow(b)):(c=b.find(".accordion-toggle").attr("href"),$.get(c,function(c){filtered=$(c).filter("#content").html();e.html(filtered);f==="impactes"&&setTimeout(recalculatePinPositions,300);doActionsForShow(b);__VOBRES.loaded[f]=
!0},"html"))}
$(document).ready(function(){$(".accordion-heading").on("click",function(f){f.preventDefault();f.stopPropagation();f.stopImmediatePropagation();f=$(this).closest(".accordion-group");f.find(".accordion-body");if(f.hasClass("visible")){var b=f.prev();hideSection(f);showSection(b)}else b=$(".visible"),hideSection(b),showSection(f)});$("#homelink").on("click",function(f){f.preventDefault();f.stopPropagation();f.stopImmediatePropagation();f=$("#home");if(!f.hasClass("visible")){var b=$(".visible");hideSection(b);
showSection(f)}});$("#collapseMiratges").on("click",".navitem",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();$this=$(this);b=parseInt($this.attr("rel"),10);$(".navitem.active").toggleClass("active",!1);$this.toggleClass("active",!0);$("#miratgesCarousel").carousel(b-1)});$("#impactesnav .forward").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();(atcarousel=$("#map").hasClass("dissolve"))?(position=$("#impactesCarousel .active.item").index(),
position<11&&(page=$($("#impactesCarousel .item").get(position+1)).attr("id"),loadImpactesPage(page),$("#impactesCarousel").carousel(position+1)),$("#impactesnav .back").toggleClass("active",position+1>0),$("#impactesnav .forward").toggleClass("active",position+1<11)):($("#bigone").toggleClass("dissolve",!1),$("#map").toggleClass("dissolve",!0),$("#impactesnav .mapa").toggleClass("active",!0),loadImpactesPage("estadi"))});$("#impactesnav .back").on("click",function(b){b.preventDefault();b.stopPropagation();
b.stopImmediatePropagation();position=$("#impactesCarousel .active.item").index();position>0&&(page=$($("#impactesCarousel .item").get(position-1)).attr("id"),loadImpactesPage(page),$("#impactesCarousel").carousel(position-1));$("#impactesnav .back").toggleClass("active",position-1>0);$("#impactesnav .forward").toggleClass("active",position-1<11)});$("#impactesnav .mapa").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();$(this).toggleClass("active",!1);$("#impactesnav .back").toggleClass("active",
!1);$("#impactesnav .forward").toggleClass("active",!0);$("#bigone").toggleClass("dissolve",!0);$("#map").toggleClass("dissolve",!1);setTimeout(function(){$("#impactesCarousel").carousel(0)},1E3);$("#impactes .accordion-toggle h3.main").text(__VOBRES.petjades_title);$("#impactes .accordion-toggle h3.sub").text("")});$("#map").on("click",".pin",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();var c=$(this).find("a").attr("href"),d=$(this).index();$("#impactesCarousel").carousel(d);
setTimeout(function(){$("#impactesnav .back").toggleClass("active",d>0);$("#impactesnav .forward").toggleClass("active",d<11);$("#impactesnav .mapa").toggleClass("active",!0);$("#map").toggleClass("dissolve",!0);$("#bigone").toggleClass("dissolve",!1);loadImpactesPage(c)},200)});$("#impactes").on("click",".goleft",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();var c=$(this).next(),b=c.find(".wrapper");c.get(0);c.width();c=Math.floor(parseInt(b.css("margin-left"),10)/
110)*-1;c>0&&(c-=1);c-=1;c>=0&&b.animate({"margin-left":c*-120},200)});$("#impactes").on("click",".goright",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();var c=$(this).prev(),b=c.find(".wrapper"),d=c.get(0).maxcols,c=Math.floor(c.width()/110),e=Math.floor(parseInt(b.css("margin-left"),10)/110)*-1;e>0&&(e-=1);e+=1;e<=d-c&&b.animate({"margin-left":e*-120},200)});$("#miratges").on("click",".goleft",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();
var b=$("#carouselNavigation").find(".wrapper"),c=parseInt(b.css("margin-left"),10)+130;console.log(c);c<0&&b.animate({"margin-left":c},200)});$("#miratges").on("click",".goright",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();var c=$("#carouselNavigation"),b=c.width(),c=c.find(".wrapper"),d=parseInt(c.css("margin-left"),10)-130;console.log(d);d*-1<1820-b&&c.animate({"margin-left":d},200)});$("#testimonis").on("click",".testimoni",function(b){b.preventDefault();b.stopPropagation();
b.stopImmediatePropagation();b=$(this);if(b.hasClass("firsttime")){b.toggleClass("firsttime",!1);var c=0}else c=1;var d=$("#testimonis .video"),e=b.attr("rel"),d=d.height()-40,h=d*1.78,n=d>500?"&vq=hd720":"",c='<div style="width:'+h+"px;height:"+d+'px; margin:20px auto;"><object id="videotestimoni" width="'+h+'" height="'+d+'"><param name="movie" value="'+e+"?version=3&amp;hl=ca_ES&amp;autoplay="+c+"&enablejsapi=1"+n+'"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param>    <embed src="'+
e+"?version=3&amp;hl=ca_ES&amp;autoplay="+c+"&enablejsapi=1"+n+'"            type="application/x-shockwave-flash"            width="'+h+'" height="'+d+'"            allowscriptaccess="always" allowfullscreen="true"></embed></object></div>';$(".testimoni.active").toggleClass("active",!1);b.toggleClass("active",!0);$("#testimonis .video").html(c)});$(window).resize(function(){var b;$("#accordion2").hasClass("athome")?b="home":b=$(".visible").attr("id");console.log(b);$("visible .accordion-body").css({height:getAvailableSize(b)});
recalculatePinPositions()});__VOBRES={status:{},loaded:{home:!0},pins:{estadi:{w:466,h:534,pop:"right"},palau:{w:437,h:532,pop:"bottom"},picornell:{w:457,h:502,pop:"top"},calatrava:{w:426,h:495,pop:"left"},ronda:{w:372,h:547,pop:"left"},platges:{w:768,h:574,pop:"right"},portolimpic:{w:652,h:575,pop:"left"},portvell:{w:584,h:553,pop:"top"},torres:{w:669,h:542,pop:"top"},vila:{w:690,h:560,pop:"right"},cinturo:{w:621,h:277,pop:"left"},collserola:{w:553,h:203,pop:"bottom"}},petjades_title:$("#impactes h3.main").text()};
var b="estadi,palau,picornell,calatrava,ronda,platges,portolimpic,portvell,torres,vila,cinturo,collserola".split(",");for(p=0;p<b.length;p++){var c=b[p],e=$(".pin#"+c).find("a");__VOBRES.pins[c].title=e.attr("title");__VOBRES.pins[c].zone=e.attr("zone");e={title:"<span>"+__VOBRES.pins[c].zone+"</span><br/>"+__VOBRES.pins[c].title,placement:__VOBRES.pins[c].pop};$(".pin#"+c).popover(e)}$(".visible .accordion-body").css({height:getAvailableSize("home")})});
function downloadFullImageFor(b){b=$(event.target).closest(".fancybox-wrap").find(".fancybox-image").attr("src");console.log(b[b.length-1])}function recalculatePinPositions(){var b=$("#map .pin");for(p=0;p<b.length;p++)recalculatePinPosition($(b[p]).attr("id"))}
function recalculatePinPosition(b){var c=$("#impactes #map").width(),e=getAvailableSize("impactes")+96,f=c/(1170/796),c=Math.floor(__VOBRES.pins[b].w*c/1170),e=Math.floor(__VOBRES.pins[b].h*f/796-(f-e)/2);$("#"+b+".pin").css({top:e-30,left:c-14})}function getAvailableSize(b){var c=0;c+=$(".navbar").outerHeight();c+=b==="home"?262:170;b==="impactes"&&(c+=37);return $(window).height()-c}
function loadImpactesPage(b){var c=$("html").attr("lang")!="ca"?"../":"";$.get("content/impactes/"+b+".json",function(e){var f=e.length,g=$("#impactes .carousel-inner"),d=getAvailableSize("impactes")-30,k=g.find("#"+b+" .pagina"),h=k.find(".wrapper"),n=g.find("#"+b+" .goleft"),g=g.find("#"+b+" .goright");k.css({height:d});n.css({height:d});g.css({height:d});maxrows=Math.floor(d/120);map=[];for(i=0;i<maxrows;i++)map[i]=[];for(i=0;i<f;i++){var d=e[i],j=getAvailablePos(d["class"]);d.type=="single"&&
h.append('<div rel="'+i+'" class="impacte '+d.type+" "+d["class"]+'" style="top:'+j.r+"px;left:"+j.c+'px"><a full="'+c+d.full+'" href="'+c+d.image+'" title="'+d.footer+'"><img src="'+c+d.thumb+'"></a><i class="emblem"></i></div>');d.type=="video"&&h.append('<div rel="'+i+'" class="impacte '+d.type+" "+d["class"]+'" style="top:'+j.r+"px;left:"+j.c+'px"><a rel="media-gallery" full="'+c+d.full+'" href="'+d.url+'" title="'+d.footer+'"><img src="'+c+d.thumb+'"></a><i class="emblem"></i></div>');if(d.type==
"serie"){var o="";for(l=1;l<d.items.length;l++)o+='<a data-fancybox-group="'+d.id+'" full="'+c+d.items[l].full+'" href="'+c+d.items[l].image+'" title="'+d.items[l].footer+'"></a>';h.append('<div rel="'+i+'" class="impacte '+d.type+" "+d["class"]+'" style="top:'+j.r+"px;left:"+j.c+'px"><a full="'+c+d.items[0].full+'"  data-fancybox-group="'+d.id+'" href="'+c+d.items[0].image+'" title="'+d.items[0].footer+'"><img src="'+c+d.thumb+'"></a>'+o+'<i class="emblem"></i></div>')}}e=Math.floor(k.width()/110);
f=getLongestRow();k.get(0).maxcols=f;f<=e&&(n.hide(),g.hide());$("#"+b+" .impacte.single a").fancybox({helpers:{title:{type:"inside"},overlay:{css:{opacity:0.8}}},closeBtn:!1,arrows:!1,afterShow:function(){var b=$(this.element),c=b.closest(".impacte"),b=b.attr("full"),c=parseInt(c.attr("rel"),10),d=$("#impactesCarousel .item").length,e=c+1,f=c-1;$(".fancybox-outer").prepend('<div class="actions">                                 <div class="prevf"></div>                                 <div class="nextf"></div>                                 <div class="download"><a href="#" target="_blank" ></div>                                 <div class="closef"></div>                             </div>');
$(".fancybox-outer .download a").attr("href",b);$(".fancybox-outer .nextf").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();e<d&&(b=$('#impactesCarousel .item.active .impacte[rel="'+e+'"] a'),$.fancybox.close(),b.trigger("click"))});$(".fancybox-outer .prevf").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();f>=0&&(b=$('#impactesCarousel .item.active .impacte[rel="'+f+'"] a'),$.fancybox.close(),b.trigger("click"))});
$(".fancybox-outer .closef").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();console.log("close");$.fancybox.close()})}});$("#"+b+" .impacte.video a").fancybox({helpers:{media:{},title:{type:"inside"},overlay:{css:{opacity:0.8}}},closeBtn:!1,arrows:!1,afterShow:function(){var b=$(this.element),c=b.closest(".impacte");b.attr("full");var b=parseInt(c.attr("rel"),10),d=$("#impactesCarousel .item").length,e=b+1,f=b-1;$(".fancybox-outer").prepend('<div class="actions">                                 <div class="prevf"></div>                                 <div class="nextf"></div>                                 <div class="closef"></div>                             </div>');
$(".fancybox-outer .nextf").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();e<d&&(b=$('#impactesCarousel .item.active .impacte[rel="'+e+'"] a'),$.fancybox.close(),b.trigger("click"))});$(".fancybox-outer .prevf").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();f>=0&&(b=$('#impactesCarousel .item.active .impacte[rel="'+f+'"] a'),$.fancybox.close(),b.trigger("click"))});$(".fancybox-outer .closef").on("click",function(b){b.preventDefault();
b.stopPropagation();b.stopImmediatePropagation();console.log("close");$.fancybox.close()})}});$("#"+b+" .impacte.serie a").fancybox({prevEffect:"none",nextEffect:"none",helpers:{thumbs:{width:50,height:50},title:{type:"inside"},overlay:{css:{opacity:0.8}}},closeBtn:!1,afterShow:function(){var b=$(this.element),c=b.closest(".impacte"),b=b.attr("full"),c=parseInt(c.attr("rel"),10),d=$("#impactesCarousel .item").length,e=c+1,f=c-1;$(".fancybox-outer").prepend('<div class="actions">                                 <div class="prevf"></div>                                 <div class="nextf"></div>                                 <div class="download"><a href="#" target="_blank" ></div>                                 <div class="closef"></div>                             </div>');
$(".fancybox-outer .download a").attr("href",b);$(".fancybox-outer .nextf").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();e<d&&(b=$('#impactesCarousel .item.active .impacte[rel="'+e+'"] a'),$.fancybox.close(),b.trigger("click"))});$(".fancybox-outer .prevf").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();f>=0&&(b=$('#impactesCarousel .item.active .impacte[rel="'+f+'"] a'),$.fancybox.close(),b.trigger("click"))});
$(".fancybox-outer .closef").on("click",function(b){b.preventDefault();b.stopPropagation();b.stopImmediatePropagation();console.log("close");$.fancybox.close()})}})},"json");$("#impactes .accordion-toggle h3.main").text(__VOBRES.pins[b].zone);$("#impactes .accordion-toggle h3.sub").text(__VOBRES.pins[b].title)}function getAvailablePos(b){(last=searchLeftMostHoleFor(b))?a=0:last=getLastPos(b);fillLastPos(b,last);return{r:last.r*120,c:last.c*120}}
function getLastPos(){var b=map[0].length;return{r:0,c:b==0?0:b}}function fillPos(b,c){if(c<map[b].length)map[b][c]=1;else{for(;map[b].length<c;)map[b].push(0);map[b].push(1)}}function fillLastPos(b,c){fillPos(c.r,c.c,1);(b=="rcc"||b=="rrcc")&&fillPos(c.r,c.c+1,1);(b=="rrc"||b=="rrcc")&&fillPos(c.r+1,c.c,1);b=="rrcc"&&fillPos(c.r+1,c.c+1,1);alignHoleMarkers()}function alignHoleMarkers(){var b=getLongestRow();for(r=0;r<maxrows;r++)for(;map[r].length<b;)map[r].push(0)}
function getLongestRow(){var b=0;for(r=0;r<maxrows;r++)if(map[r].length>b)b=map[r].length;return b}function isLefterThan(b,c,e){return b?e<b.c?!0:!1:!0}function searchLeftMostHoleFor(b){var c=!1;for(sr=0;sr<maxrows;sr++){var e=map[sr];for(sc=0;sc<e.length;sc++)e[sc]==0&&tileFits(b,sr,sc)&&isLefterThan(c,sr,sc)&&(c={r:sr,c:sc})}return c?c:!1}
function tileFits(b,c,e){fits=isAvailable(c,e);if(b=="rrcc"||b=="rcc")fits=fits&&isAvailable(c,e+1);if(b=="rrcc"||b=="rrc")fits=fits&&isAvailable(c+1,e);b=="rrcc"&&(fits=fits&&isAvailable(c+1,e+1));return fits}function isAvailable(b,c){return b>=maxrows?!1:c<map[b].length?map[b][c]==0:!0};
